TRANSLATIONS = {
    'ru': {
        'language': 'Язык',
        'mode': 'Режим',
        'sound': 'Танцевать под звук',
        'system': 'Русский',
        'layers': 'Слои',
        'on_top': 'Поверх всех окон',
        'standard': 'Стандарт',
        'sound_play': 'Звуки',
        'loop': 'Цикл',
        'shadow': 'Тень',
        'rainbow': 'Радуга',
        'blue_shadow': 'Голубая тень',
        'size': 'Размер',
        'size_title': 'Размер Фумо',
        'speed':'Скорость',
        'speed_title':'Скорость Фумо',
        'speed_captions': ["Размеренно..", "Чил", "Стандарт", "Быстро!", "Безумно", "⑨ MODE"],
        'exit': 'Выход',
        'autostart':'Автозапуск'
    },
    'en': {
        'language': 'Language',
        'mode': 'Mode',
        'sound': 'Dance on sound',
        'system': 'English',
        'layers': 'Layers',
        'on_top': 'Always on top',
        'standard': 'Standard',
        'sound_play': 'Sounds',
        'loop': 'Loop',
        'shadow': 'Shadow',
        'rainbow': 'Rainbow',
        'blue_shadow': 'Blue Shadow',
        'size': 'Size',
        'size_title': 'Fumo Size',
        'speed':'Speed',
        'speed_title':'Fumo Speed',
        'speed_captions': ["Faster, please!", "Chill", "Standard", "Gotta go fast!", "Insane Dance", "⑨ MODE"],
        'exit': 'Exit',
        'autostart':'Autostart'
    },
    'ja': {
        'language': '言語',
        'mode': 'モード',
        'sound': '音に合わせて踊る',
        'system': '日本語',
        'layers': 'レイヤー',
        'on_top': '常に手前に表示',
        'standard': '標準',
        'sound_play': '音',
        'loop': 'ループ',
        'shadow': '影',
        'rainbow': '虹',
        'blue_shadow': '青い影',
        'size': 'サイズ',
        'size_title': 'ふもサイズ',
        'speed':'スピード',
        'speed_title':'フモのスピード',
        'speed_captions': ["もっと早く！", "まったり", "標準", "速く！", "狂気のダンス", "⑨"],
        'exit': '終了',
        'autostart':'自動起動'
    },
    'zh': {
        'language': '语言',
        'mode': '模式',
        'sound': '随声音起舞',
        'system': '中文',
        'layers': '图层',
        'on_top': '置顶',
        'standard': '标准',
        'sound_play': '音频',
        'loop': '循环',
        'shadow': '阴影',
        'rainbow': '彩虹',
        'blue_shadow': '蓝色阴影',
        'size': '尺寸',
        'size_title': 'Fumo尺寸',
        'speed':'速度',
        'speed_title':'弗莫的速度',
        'speed_captions': ["请快点！", "冷静", "标准", "快点！", "疯狂起舞", "⑨"],
        'exit': '退出',
        'autostart':'开机自启'
    },
    'es': {
        'language': 'Idioma',
        'mode': 'Modo',
        'sound': 'Bailar con sonido',
        'system': 'Español',
        'layers': 'Capas',
        'on_top': 'Siempre arriba',
        'standard': 'Estándar',
        'sound_play': 'Sonido',
        'loop': 'Bucle',
        'shadow': 'Sombra',
        'rainbow': 'Arcoíris',
        'blue_shadow': 'Sombra azul',
        'size': 'Tamaño',
        'size_title':'Tamaño de Fumo',
        'speed':'Velocidad',
        'speed_title':'La velocidad de Fumo',
        'speed_captions': ["¡Más rápido!", "Chill", "Estándar", "¡A toda prisa!", "Danza loca", "⑨ MODE"],
        'exit': 'Salir',
        'autostart':'Autoinicio'
    },
    'pt': {
        'language': 'Idioma',
        'mode': 'Modo',
        'sound': 'Dançar com som',
        'system': 'Português',
        'layers': 'Camadas',
        'on_top': 'Sempre no topo',
        'standard': 'Padrão',
        'sound_play': 'Som',
        'loop': 'Loop',
        'shadow': 'Sombra',
        'rainbow': 'Arco-íris',
        'blue_shadow': 'Sombra azul',
        'size': 'Tamanho',
        'size_title':'Tamanho Fumo',
        'speed':'Velocidade',
        'speed_title':'A velocidade de Fumo',
        'speed_captions': ["Mais", "Chill", "Padrão", "Gotta go fast!", "Dança insana", "⑨ MODE"],
        'exit': 'Sair',
        'autostart':'Autoiniciar'
    },
    'de': {
        'language': 'Sprache',
        'mode': 'Modus',
        'sound': 'Zu Sound tanzen',
        'system': 'Deutsch',
        'layers': 'Ebenen',
        'on_top': 'Immer oben',
        'standard': 'Standard',
        'sound_play': 'Ton',
        'loop': 'Schleife',
        'shadow': 'Schatten',
        'rainbow': 'Regenbogen',
        'blue_shadow': 'Blaue Schatten',
        'size': 'Größe',
        'size_title':'Fumo-Größe',
        'speed':'Geschwindigkeit',
        'speed_title':'Fumos Geschwindigkeit',
        'speed_captions': ["Schneller, bitte!", "Chill", "Standard", "Gotta go fast!", "Verrückter Tanz", "⑨ MODE"],
        'exit': 'Beenden',
        'autostart':'Autostart'
    }
}